sudo: false
language: go
services:
- redis-server
go:
- 1.5
notifications:
  slack:
    secure: a8rVLC/cwfmkS/+Sm5jkz2itadufARnLe4d5i/yRQPE9MvDgPeW1WGplCcuVLQJRM3g8CVeEeJu87Igk6RZ3HZwutNTobFYh5jsWz5OfAJMo5nXX99o8708nO2GzvK6xwmtVYfGixPuhX5r3gsu05Gs3v0SpnxgnXhVhD8DUovVZobl4IIe2wDVyZi+eGvjfHbn/hYyD8CgKkWGxQo+KZQpJGNk2X0/7EFnKmOlX9A/5IQ5Md2CJRpyrNXUq9ClqkDUpwWss3T9ry9/5s3oJkuaMqxPgQ4Fe4HU3GE8X2VEKcsX3MB+i+kVrn3e0u1kCbIx9KOIQyf5ap4pSebzxM2d0Yj79ygWHZe/rRXrd6HMBSxkGQqbW2ZMfJ0q5qZedUdNGxOrp8+/e9gQVYpoRs+xGq38jYUqdJaa0UjE6MAEXyLKAWCduuzz2xu7TrIi0yb6dXBBzpMuZxxh+7+wIz2PdlxYgkJFrKZyloGjfucMSEIMz+LUKwhQUN+4Xx4l/QvMr7TtdTHg58nh9IWrE/cfF8s2F2S5k9vbc40ursT6zDUN4oGyP1tokl0EBBSMY1HLgh3tCmez/j0dbMT4WE+HFApYwDi+HWHNEQP/FR2YQhZ/WNKHjYv1mNP4gNwsXla/bYD3YUDVTrDmqx4NkrwpJUglhq886/0um/T3TiC8=
